### PR TITLE
functionality to disable maps button

### PR DESCRIPTION
**Pull request by RoyMontoya**

### CODE REVIEW

**Comment by jmsalcido** [comment]
on which class is this going to be added? day 3? day 4? day 5?, which issue does it fix?

**Comment by RoyMontoya** [comment]
this implementation is part of class 5, instead of making another PR i ll merge it into the location branch, feel free to close the PR.

**Comment by jmsalcido** [comment]
>this implementation is part of class 5, instead of making another PR i ll merge it into the location branch, feel free to close the PR.

you can close it too

**Comment by RoyMontoya** [comment]
@jmsalcido i did close it, but i was afraid that you weren't able to see the comment, so i reopen at and commented it.

**Pull request closed without merging**
